apiVersion: v1
kind: Service
metadata:
    name: gotinyurl-service
spec:
    type: NodePort
    selector:
        app: gotinyurl
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 30080
